import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import WorkExperience from '../components/WorkExperience'

export default function Home() {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0'>
      <Head>
        <title>Aris Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/* Header */}
      <Header />


      {/* Hero */}
      <section className='snap-start' id="hero">
        <Hero />
      </section>
      {/* About */}

      <section className='snap-center' id='about'>
        <About />
      </section>

      {/* Experience */}
      <section className='snap-center' id='experince'>
        <WorkExperience />
      </section>

      {/* Skills */}

      {/* Projects */}

      {/* Contact me */}
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
